name: Test

# on:
#   push:
#     branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Aftman
        uses: ok-nick/setup-aftman@c52e3c91524316f8ca696574d576ea21b7518ec8 # tag=v0.3.0
        with:
          version: v0.3.0

      - name: Lint
        run: |
          EXIT_STATUS=0
          ./actionlint -ignore 'SC2153:' || EXIT_STATUS=$?
          selene src || EXIT_STATUS=$?
          exit $EXIT_STATUS