name: Test

# on:
#   push:
#     branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Aftman
        uses: ok-nick/setup-aftman@e226f24209f47677da7b215bab44f6351a2c043b # v0.4.2
        with:
          version: v0.1.0

      - name: Lint
        run: |
          EXIT_STATUS=0
          ./actionlint -ignore 'SC2153:' || EXIT_STATUS=$?
          selene src || EXIT_STATUS=$?
          exit $EXIT_STATUS